routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/tours/{filter?}', 'TourController@index')->name('tour.list')->where('filter', '(.*)?');

Route::get('/tour/{id}', 'TourController@show')->name('tour.show');
Route::post('/tour/{id}/registration', 'TourController@storeRegistration')->name('tour.registration');



Route::group(['prefix' => 'me', 'middleware' => 'auth', 'as' => 'me.'], function () {
	Route::get('/', 'MeController@index')->name('index');
	Route::get('/registrations', 'MeController@registrations')->name('registrations');
	Route::resource('tour', 'TourController', [
		'except' => [ 'index', 'show', 'makeRegistration'], 
		'names' => [
	    	//'create' => 'photo.build'
		]
	]);
});

Route::get('/auth/fb/callback', 'Auth\FacebookController@handleProviderCallback')->name('auth.facebook.callback');
Route::get('/auth/fb', 'Auth\FacebookController@redirectToProvider')->name('auth.facebook');
Auth::routes();

resources/views/layouts/partials/flash.blade.php
@if (Session::has('flash_message'))
    <div class="alert alert-success alert-dismissible fade in  margin-top-20" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        {{ Session::get('flash_message') }}
    </div>
@endif
@if (Session::has('flash_error'))
    <div class="alert alert-danger alert-dismissible fade in margin-top-20" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        {{ Session::get('flash_error') }}
    </div>
@endif

resources/views/layouts/partials/footer.blade.php
<div class="container">
    <nav class="pull-left">
        <ul>
            <li class="active">
                <a href="/">Главная</a>
            </li>
            <li>
                <a href="/courses">Курсы</a>
            </li>
            <li>
                <a href="/schools">Школы</a>
            </li>
        </ul>
    </nav>
    <div class="social-btns pull-right">
        <a href="http://facebook.com/tripicoua" rel="nofollow"><div class="fui-facebook"></div><div class="fui-facebook"></div></a>
    </div>
    <div class="additional-links">

        Если вы представитель курсов - напишите на почту и мы разместим ваш ресурс
    </div>
</div>

resources/views/layouts/partials/nav.blade.php
<nav id="layout-nav" class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Tripico</a>
        </div>
        <div class="collapse navbar-collapse navbar-main-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{{ route('tour.list') }}" class="">
                        Всі поїздки
                    </a>
                </li>
                <li class="">
                    <a href="{{ route('me.tour.create') }}">
                        <span class="fui-plus"></span>
                        <span>Додати тур</span>
                    </a>
                </li>


                @if (Auth::guest())
                    <li class="">
                        <a href="{{ route('auth.facebook') }}">fb</a>
                    </li>
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <img src="{{ Auth::user()->image_thumb_url }}" width="26px" class="img-circle" style="margin-right:10px;vertical-align: top;">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('me.index') }}">
                                    Мої тури
                                </a>
                                <a href="{{ url('/logout') }}"
                                    onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                    Вийти
                                </a>

                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
                {{-- {% if user %}
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello,   <b class="caret"></b></a>
                    <span class="dropdown-arrow"></span>
                    <ul class="dropdown-menu">
                        <li><a data-request="onLogout">Sign out</a></li>
                    </ul>
                </li>
                {% endif %}   --}}              
            </ul>
        </div>
    </div>
</nav>