routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/tours/{filter?}', 'TourController@index')->name('tour.list')->where('filter', '(.*)?');

Route::get('/tour/{id}', 'TourController@show')->name('tour.show');
Route::post('/tour/{id}/registration', 'TourController@storeRegistration')->name('tour.registration');



Route::group(['prefix' => 'me', 'middleware' => 'auth', 'as' => 'me.'], function () {
	Route::get('/', 'MeController@index')->name('index');
	Route::get('/registrations', 'MeController@registrations')->name('registrations');
	Route::resource('tour', 'TourController', [
		'except' => [ 'index', 'show', 'makeRegistration'], 
		'names' => [
	    	//'create' => 'photo.build'
		]
	]);
});

Route::get('/auth/fb/callback', 'Auth\FacebookController@handleProviderCallback')->name('auth.facebook.callback');
Route::get('/auth/fb', 'Auth\FacebookController@redirectToProvider')->name('auth.facebook');
Auth::routes();

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;
use App\Helpers\Filter;
use Collective\Html\Eloquent\FormAccessible;

class Tour extends Model
{
    use FormAccessible;
    use \KodiComponents\Support\Upload;

    protected $fillable = [
        'title', 'description',  'program', 'slug', 'starts_at', 'days', 'from_id', 'image', 'image_thumb', 'upload_image', 'included', 'excluded'
    ];

    protected $guarded = [
        '*'
    ];

    protected $dates = [
        'starts_at'
    ];

    protected $casts = [
        'image' => 'image',
        'image_thumb' => 'image',
    ];

    public function getUploadSettings()
    {
        return [
            'image' => [
                'orientate' => [],
                'fit' => [420, 315, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                }]
            ],
            'image_thumb' => [
                'orientate' => [],
                'fit' => [75, 75, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                }]
            ]
        ];
    }



    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('current', function(Builder $builder) {
            $builder->where('starts_at', '>', Carbon::now());
        });

        static::addGlobalScope('order', function(Builder $builder) {
            $builder->orderBy('starts_at', 'asc');
        });
    }


    /*
    		Relations
    */

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function trip_types()
    {
        return $this->belongsToMany('App\TripType');
    }

    public function from()
    {
        return $this->hasOne('App\Location', 'id', 'from_id');
    }


    		// Many

    public function to()
    {
        return $this->belongsToMany('App\Location');
    }
    
    public function prices()
    {
        return $this->hasMany('App\Price', 'tour_id')->orderBy('price', 'asc');
    }

    public function registrations()
    {
        return $this->hasMany('App\Registration', 'tour_id')->orderBy('created_at', 'desc');;
    }


    /*
            Scopes
    */


    public function ScopeWithArchive($query)
    {
        return $query->withoutGlobalScope('current');
    }

    public function ScopeOnlyArchive($query)
    {
        return $query->withoutGlobalScope('current')->where('starts_at', '<', Carbon::now());
    }

    public function ScopeReverse($query)
    {
        return $query->orderBy('starts_at', 'desc');;
    }

    public function ScopeFiltered($query, $filter = null)
    {
        if (!$filter)
            return $query;

        foreach ($filter->get() as $key => $value) {
            $f_name = camel_case('filter_' . $key);
            
            $query->$f_name($value);
        }
        return $query;
    }

    public function ScopeFilterFrom($query, $value)
    {
        return $query->whereHas('from', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }

    public function ScopeFilterTo($query, $value)
    {
        return $query->whereHas('to', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }

    public function ScopeFilterType($query, $value)
    {
        return $query->whereHas('trip_types', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }


    /*
    		Getters & setters
    */
    public function setStartsAtAttribute($value)
    {
        $this->attributes['starts_at'] = Carbon::parse($value)->endOfDay();
    }


    public function setProgramAttribute($value)
    {
    	$this->attributes['program'] = json_encode($value);
    }

    public function getProgramAttribute($value)
    {
    	return json_decode($value);
    }


    public function setIncludedAttribute($value)
    {
        $this->attributes['included'] = json_encode($value);
    }

    public function getIncludedAttribute($value)
    {
        return json_decode($value);
    }

    public function getIsArchiveAttribute($value)
    {
        return ($this->starts_at < Carbon::now());
    }


    public function setExcludedAttribute($value)
    {
        $this->attributes['excluded'] = json_encode($value);
    }

    public function getExcludedAttribute($value)
    {
        return json_decode($value);
    }


    public function getPriceMinAttribute()
    {
    	return $this->prices()->first();
    }



    /*
            Form Data
    */


    public function formStartsAtAttribute($value)
    {
        return Carbon::parse($value)->format('Y-m-d');
    }

    public function formToAttribute($value)
    {
        return $this->to()->get()->pluck('id')->toArray();
    }

    public function formFromAttribute($value)
    {
        return $this->from()->get()->pluck('id')->toArray();
    }

    public function formTripTypesAttribute($value)
    {
        return $this->trip_types()->get()->pluck('id')->toArray();
    }


    /**
     * @param \Illuminate\Http\UploadedFile $file
     */
    public function setUploadImageAttribute(\Illuminate\Http\UploadedFile $file = null)
    {
        if (is_null($file)) {
            return;
        }

        foreach ($this->getUploadFields() as $field) {
            $this->{$field.'_file'} = $file;
        }
    }


    public function updateManyRelations($request)
    {
        $this->to()->sync(($request->input('to')) ? : [] );
        $this->trip_types()->sync(($request->input('trip_types')) ? : []);
        $this->prices()->delete();
        foreach ($request->input('prices') as $key => $value) {
            $this->prices()->create($value);
        }
        
    }

}

app/Http/Controllers/MeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Registration;
use App\Tour;

class MeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['user'] = Auth::user();
        $data['secondary_menu'] = "index";
        $data['title'] = "Мої тури";
        $data['tours'] = $data['user']->tours()->withArchive()->reverse()->get();
        return view('me.index', $data);
    }


    public function registrations()
    {
        $data = [];
        $data['registrations'] = Registration::all();
        $data['secondary_menu'] = "registrations";
        $data['title'] = "Реєстрації на мої тури";
        return view('me.registrations', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/me/_secondary_menu.blade.php
<?php if(!isset($secondary_menu)) $secondary_menu = null; ?>
<div class="row margin-top-30 margin-bottom-20">
    <div class="col-md-6">
        <h2 class="margin-top-0">{{ (isset($title)) ? $title : ' '}}</h2>
    </div>
    <div class="col-md-6">
        <ul class="nav nav-pills pull-right margin-top-10">
            <li role="presentation" @if($secondary_menu == 'new')class="active" @endif>
                <a href="{{ route('me.tour.create') }}">
                    <span class="fui-plus"></span>
                    <span>Додати тур</span>
                </a>
            </li>
            <li role="presentation" @if($secondary_menu == 'index')class="active" @endif>
                <a href="{{ route('me.index') }}">Мої тури</a>
            </li>
            <li role="presentation" @if($secondary_menu == 'registrations')class="active" @endif>
                <a href="{{ route('me.registrations') }}">Реєстрації</a>
            </li>
        </ul>
    </div>
</div>

resources/views/me/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container me-page">
    @include('me._secondary_menu')

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive table-hover">
                <table class="table margin-bottom-40">
                    <thead>
                        <tr>
                            <td></td>
                            <td>Назва</td>
                            <td>Дата</td>
                            <td>Кіл-сть днів</td>
                            <td>Звідки</td>
                            <td>Реєстрацій</td>
                        </tr>
                    </thead>
                    @foreach($tours as $tour)
                        
                        <tr class="{{ $tour->is_archive ? 'disabled' : '' }}">
                            
                            <td width="70px"><img src="{{ $tour->image_thumb_url }}" height="40px"></td>
                            <td>
                                <a href="{{ route('me.tour.edit', $tour) }}">{{ $tour->title }}</a>
                            </td>
                            <td>{{ $tour->starts_at->format('d.m.y') }}</td>
                            <td>{{ $tour->days }}</td>
                            <td>{{ $tour->from->name }}</td>
                            <td>{{ $tour->registrations->count() }}</td>

                        </tr>
                        
                    @endforeach
                </table>
            </div>
        </div>
    </div>
    
    
</div>

@endsection

resources/views/me/registrations.blade.php
@extends('layouts.app')

@section('content')

<div class="container me-page">
    @include('me._secondary_menu')

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                @if ($registrations->count())
                <table class="table ">
                    <thead>
                        <tr>
                            
                            <td>Назва туру</td>
                            <td>Ім'я</td>
                            <td>Телефон</td>
                            <td>e-mail</td>
                            <td>К-сть людей</td>
                            <td>Ціна</td>
                            <td>Опис ціни</td>
                            <td>Дата</td>
                        </tr>
                    </thead>
                    @foreach($registrations as $item)
                        
                        <tr>
                            
                            
                            
                            
                            <td>
                                <a href="{{ route('tour.show', $item->tour) }}">
                                    <img class="img-circle" src="{{ $item->tour->image_thumb_url }}" width="30" height="30">
                                    {{ $item->tour->title }}
                                </a>
                                
                            </td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->phone }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->people_count }}</td>
                            <td>{{ $item->price }}</td>
                            <td>{{ $item->price_title }}</td>
                            <td>
                                {{ $item->created_at->format('d.m.y') }}
                                <span class="text-muted">{{ $item->created_at->format('H:i') }}</span>
                            </td>

                        </tr>
                        
                    @endforeach
                </table>
                @else
                    <h4 class="text-center margin-top-40 text-muted">Нажаль, в вас ще немає реєстрацій</h4>
                    
                @endif
            </div>
        </div>
    </div>
    
    
</div>

@endsection