routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/tours/{filter?}', 'TourController@index')->name('tour.list')->where('filter', '(.*)?');

Route::get('/tour/{id}', 'TourController@show')->name('tour.show');
Route::post('/tour/{id}/registration', 'TourController@storeRegistration')->name('tour.registration');



Route::group(['prefix' => 'me', 'middleware' => 'auth', 'as' => 'me.'], function () {
	Route::get('/', 'MeController@index')->name('index');
	Route::get('/registrations', 'MeController@registrations')->name('registrations');
	Route::resource('tour', 'TourController', [
		'except' => [ 'index', 'show', 'makeRegistration'], 
		'names' => [
	    	//'create' => 'photo.build'
		]
	]);
});

Route::get('/auth/fb/callback', 'Auth\FacebookController@handleProviderCallback')->name('auth.facebook.callback');
Route::get('/auth/fb', 'Auth\FacebookController@redirectToProvider')->name('auth.facebook');
Auth::routes();

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Carbon\Carbon;
use App\Helpers\Filter;
use Collective\Html\Eloquent\FormAccessible;

class Tour extends Model
{
    use FormAccessible;
    use \KodiComponents\Support\Upload;

    protected $fillable = [
        'title', 'description',  'program', 'slug', 'starts_at', 'days', 'from_id', 'image', 'image_thumb', 'upload_image', 'included', 'excluded'
    ];

    protected $guarded = [
        '*'
    ];

    protected $dates = [
        'starts_at'
    ];

    protected $casts = [
        'image' => 'image',
        'image_thumb' => 'image',
    ];

    public function getUploadSettings()
    {
        return [
            'image' => [
                'orientate' => [],
                'fit' => [420, 315, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                }]
            ],
            'image_thumb' => [
                'orientate' => [],
                'fit' => [75, 75, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                }]
            ]
        ];
    }



    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('current', function(Builder $builder) {
            $builder->where('starts_at', '>', Carbon::now());
        });

        static::addGlobalScope('order', function(Builder $builder) {
            $builder->orderBy('starts_at', 'asc');
        });
    }


    /*
    		Relations
    */

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }

    public function trip_types()
    {
        return $this->belongsToMany('App\TripType');
    }

    public function from()
    {
        return $this->hasOne('App\Location', 'id', 'from_id');
    }


    		// Many

    public function to()
    {
        return $this->belongsToMany('App\Location');
    }
    
    public function prices()
    {
        return $this->hasMany('App\Price', 'tour_id')->orderBy('price', 'asc');
    }

    public function registrations()
    {
        return $this->hasMany('App\Registration', 'tour_id')->orderBy('created_at', 'desc');;
    }


    /*
            Scopes
    */


    public function ScopeWithArchive($query)
    {
        return $query->withoutGlobalScope('current');
    }

    public function ScopeOnlyArchive($query)
    {
        return $query->withoutGlobalScope('current')->where('starts_at', '<', Carbon::now());
    }

    public function ScopeReverse($query)
    {
        return $query->orderBy('starts_at', 'desc');;
    }

    public function ScopeFiltered($query, $filter = null)
    {
        if (!$filter)
            return $query;

        foreach ($filter->get() as $key => $value) {
            $f_name = camel_case('filter_' . $key);
            
            $query->$f_name($value);
        }
        return $query;
    }

    public function ScopeFilterFrom($query, $value)
    {
        return $query->whereHas('from', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }

    public function ScopeFilterTo($query, $value)
    {
        return $query->whereHas('to', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }

    public function ScopeFilterType($query, $value)
    {
        return $query->whereHas('trip_types', function ($query) use ($value) {
                $query->whereSlug($value);
            });
    }


    /*
    		Getters & setters
    */
    public function setStartsAtAttribute($value)
    {
        $this->attributes['starts_at'] = Carbon::parse($value)->endOfDay();
    }


    public function setProgramAttribute($value)
    {
    	$this->attributes['program'] = json_encode($value);
    }

    public function getProgramAttribute($value)
    {
    	return json_decode($value);
    }


    public function setIncludedAttribute($value)
    {
        $this->attributes['included'] = json_encode($value);
    }

    public function getIncludedAttribute($value)
    {
        return json_decode($value);
    }

    public function getIsArchiveAttribute($value)
    {
        return ($this->starts_at < Carbon::now());
    }


    public function setExcludedAttribute($value)
    {
        $this->attributes['excluded'] = json_encode($value);
    }

    public function getExcludedAttribute($value)
    {
        return json_decode($value);
    }


    public function getPriceMinAttribute()
    {
    	return $this->prices()->first();
    }



    /*
            Form Data
    */


    public function formStartsAtAttribute($value)
    {
        return Carbon::parse($value)->format('Y-m-d');
    }

    public function formToAttribute($value)
    {
        return $this->to()->get()->pluck('id')->toArray();
    }

    public function formFromAttribute($value)
    {
        return $this->from()->get()->pluck('id')->toArray();
    }

    public function formTripTypesAttribute($value)
    {
        return $this->trip_types()->get()->pluck('id')->toArray();
    }


    /**
     * @param \Illuminate\Http\UploadedFile $file
     */
    public function setUploadImageAttribute(\Illuminate\Http\UploadedFile $file = null)
    {
        if (is_null($file)) {
            return;
        }

        foreach ($this->getUploadFields() as $field) {
            $this->{$field.'_file'} = $file;
        }
    }


    public function updateManyRelations($request)
    {
        $this->to()->sync(($request->input('to')) ? : [] );
        $this->trip_types()->sync(($request->input('trip_types')) ? : []);
        $this->prices()->delete();
        foreach ($request->input('prices') as $key => $value) {
            $this->prices()->create($value);
        }
        
    }

}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tour;
use App\Location;
use App\TripType;
use App\Helpers\Filter;
use App\Price;
use Illuminate\Support\Facades\Auth;

class TourController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($filter_string = null)
    {
        
        $filter = null;
        
        $data['filter'] = [];
        $h1_text = 'Всі тури по Україні';
        if ($filter_string){
            $filter = new Filter($filter_string);
            if ($filter->error)
                return abort('404');
            $data['filter'] = $filter->get();

            $data['filter'] = $filter->GetFilterObjects();
            $filterObj = $data['filter'];
            $h1_text  = (isset($filterObj['type'])) ? $filterObj['type']->title         : 'Всі тури';
            $h1_text .= (isset($filterObj['to']))   ? ' в ' . $filterObj['to']->name    : ' по Україні';
            $h1_text .= (isset($filterObj['from']))  ? ' з ' . $filterObj['from']->name : '';
        }


        $data['tours'] = Tour::filtered($filter)->get();

        $data['h1_text'] = $h1_text;



        $data['location_to'] = Location::getAllWithRelationCount('tours_to');
        $data['location_from'] = Location::getAllWithRelationCount('tours_from');
        $data['trip_types'] = TripType::getAllWithRelationCount('tours');

        return view('tours.list.index', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!$data['tour'] = Tour::find($id))
            return abort('404');

        return view('tours.show.index', $data);
    }



    public function storeRegistration(Request $request, $id)
    {
        if (!$tour = Tour::find($id))
            return abort('404');

        if ($tour->registrations()->create($request->all()))
            \Session::flash('flash_message', 'Вітаємо, ви зареєструвались на тур ' . $tour->title);

        return redirect()->route('tour.show', $tour);
    }





    /**
     *    Admin part
     *
    */


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['tour'] = null;

        $data['title'] = "Створення нового туру";
        $data['arr_to'] = Location::pluck('name', 'id');
        $data['arr_trip_types'] = TripType::pluck('title', 'id');

        return view('tours.admin.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        
        if ($tour = Auth::user()->tours()->create($request->all()))
            \Session::flash('flash_message', 'Тур було створено!');

        $tour->updateManyRelations($request);

        return redirect()->route('me.tour.edit', $tour->id);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$data['tour'] = Tour::WithArchive()->find($id))
            return abort('404');

        $data['title'] = "Зміна тура " . $data['tour']->title;

        $data['arr_to'] = Location::pluck('name', 'id');
        $data['arr_trip_types'] = TripType::pluck('title', 'id');
        

        return view('tours.admin.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        if (!$tour = Tour::WithArchive()->find($id))
            return abort('404');

        if ($tour->update($request->all()))
            \Session::flash('flash_message', 'Тур було оновлено!');

        $tour->updateManyRelations($request);

        return redirect()->back();


    }

    

    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tours/admin/_form.blade.php
<div class="row form">
	<div class="col-lg-10 col-lg-offset-1 ">
		<div class="block-20 border-1">
			<div>

			  <!-- Nav tabs -->
			    <ul class="nav nav-tabs" role="tablist">
				    <li role="presentation"  class="active"><a href="#main" aria-controls="main" role="tab" data-toggle="tab">Основні</a></li>
				    <li role="presentation"><a href="#price" aria-controls="price" role="tab" data-toggle="tab">Ціни</a></li>
				    <li role="presentation"><a href="#program" aria-controls="program" role="tab" data-toggle="tab">Програма</a></li>
				    <li role="presentation"><a href="#included" aria-controls="included" role="tab" data-toggle="tab">Включено</a></li>
			    </ul>
			</div>

			<!-- Tab panes -->
		    <div class="tab-content">
			    <div role="tabpanel" class="tab-pane fade in active" id="main">
				    
					<div class="row">
						<div class="col-md-8">
							<div class="form-group big">
								{{ Form::label('Назва туру', '', ['class' => 'col-sm-4 control-label']) }}
								<div class=" col-sm-8">
									{{ Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Новий Рік в Карпатах', 'required' => '']) }}
								</div>
							</div>

							

							<div class="form-group small">
								{{ Form::label('Дата подорожі', '', ['class' => 'col-sm-4 control-label']) }}
								<div class=" col-sm-4">
									{{ Form::date('starts_at', null, ['class' => 'form-control', 'placeholder' => '', 'required' => '']) }}
								</div>
								{{ Form::label('Днів', '', ['class' => 'col-sm-1 control-label']) }}
								<div class=" col-sm-3">
									
									{!! Form::select('days', range(1,20), null, ['class' => 'form-control ', 'required' => '']) !!}
								</div>
							</div>

							<div class="form-group small">
								{{ Form::label('Звідки', '', ['class' => 'col-sm-4 control-label']) }}
								<div class=" col-sm-8">
									{!! Form::select('from_id', $arr_to, null, ['class' => 'form-control select2', 'required' => '']) !!}
								</div>
							</div>

							<div class="form-group">
								{{ Form::label('Куди їдемо', '', ['class' => 'col-sm-4 control-label']) }}
								<div class=" col-sm-8">
									{!! Form::select('to[]', $arr_to, null, ['class' => 'form-control select2', 'multiple'=>'', 'required' => '']) !!}
								</div>
							</div>

							<div class="form-group small">
								{{ Form::label('Тип подорожі', '', ['class' => 'col-sm-4 control-label']) }}
								<div class=" col-sm-8">
									{!! Form::select('trip_types[]', $arr_trip_types, null, ['class' => 'form-control select2', 'multiple'=>'']) !!}
								</div>
							</div>

							<div class="form-group">
								{{ Form::label('Опис поїдки', '', ['class' => 'col-sm-4 control-label bold']) }}
								<div class=" col-sm-8">
									{!! Form::textarea('description',  null, ['class' => 'form-control', 'required' => '']) !!}
								</div>
							</div>

							


							
						</div>
						<div class="col-md-4 col-sm-offset-4 col-md-offset-0">
							<div class="form-group">
								<div class=" col-sm-12">
								
								
									<image_input name="upload_image" image-src="{{ ($tour) ? (($tour->image_url) ? : '') : '' }}"></image_input>
								</div>
								
							</div>
						</div>
					</div>


				</div>
				
				<div role="tabpanel" class="tab-pane fade" id="price">
					<div class="row">
						<div class="col-md-8">
							<div class="form-group ">
								{{ Form::label('Ціни', '', ['class' => 'col-sm-4 control-label big']) }}
								<div class=" col-sm-8">
									<tour-prices list_json="{{ ($tour) ? $tour->prices()->select('price', 'title', 'id')->get()->toJson() : '' }}"></tour-prices>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div role="tabpanel" class="tab-pane fade" id="program">
					<div class="row">
						<div class="col-md-12">
							<div class="form-group ">
								
								<div class=" col-sm-12">
									{{ Form::label('Програма', '', ['class' => 'control-label big']) }}
									<tour-program list_json="{{ ($tour) ? json_encode($tour->program) : '' }}"></tour-prices>
								</div>
							</div>
						</div>
					</div>
				</div>


				<div role="tabpanel" class="tab-pane fade" id="included">
					<div class="row">
						<div class="col-md-12">
							<div class="form-group ">
								
								<div class=" col-sm-6">
									{{ Form::label('Включено', '', ['class' => 'control-label big']) }}
									<tour-included list_json="{{ ($tour) ? json_encode($tour->included) : '' }}" name="included"></tour-included>
								</div>
								<div class=" col-sm-6">
									{{ Form::label('Невключено', '', ['class' => 'control-label big']) }}
									<tour-included list_json="{{ ($tour) ? json_encode($tour->excluded) : '' }}" name="excluded"></tour-included>
								</div>
							</div>
						</div>
					</div>
				</div>


			</div>

			<div class="row">
				<div class="col-md-8">
					<div class="form-group">
						<div class="col-sm-8 col-sm-offset-4">
						{{ Form::submit('Зберегти',  ['class' => "btn btn-warning btn-lg"]) }}
						</div>
					</div>
				</div>
			</div>

			

			

			

		</div>
	</div>
</div>


@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
@endsection


@section('scripts')
	<script>
		$('select.select2').select2();
	</script>
@endsection

resources/views/tours/admin/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container admin-tours create" >
	@include('me._secondary_menu')
	{!! Form::open(['url' => route('me.tour.store'), 'method' => 'POST', 'enctype'=>"multipart/form-data", 'class'=>'form-horizontal']) !!}
		@include('tours.admin._form')
	{!! Form::close() !!}
</div>
@endsection

resources/views/tours/admin/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container admin-tours edit">
	@include('me._secondary_menu')		
	{!! Form::model($tour, ['url' => route('me.tour.update', $tour), 'method' => 'put', 'enctype'=>"multipart/form-data", 'class'=>'form-horizontal']) !!}
		@include('tours.admin._form')
	{!! Form::close() !!}
</div>

@endsection